<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-05-16 15:03
=======
# Generated by Django 5.2.1 on 2025-05-14 14:39
>>>>>>> 898b6e2a1bd209f40d908a0818993448821f98b6

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
