# Generated by Django 5.1.3 on 2025-05-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='kaybettim_hakki',
            field=models.IntegerField(default=5),
        ),
    ]
