# Generated by Django 5.1.3 on 2025-03-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanim', models.CharField(default='Belirtilmedi', max_length=255, verbose_name='Eşya Tanımı')),
                ('tur', models.CharField(choices=[('canta', 'Çanta'), ('telefon', 'Telefon'), ('cuzdan', 'Cüzdan'), ('diger', 'Diğer')], default='diger', max_length=50, verbose_name='Eşya Türü')),
                ('renk', models.CharField(choices=[('siyah', 'Siyah'), ('beyaz', 'Beyaz'), ('mavi', 'Mavi'), ('kirmizi', 'Kırmızı'), ('diger', 'Diğer')], default='diger', max_length=50, verbose_name='Eşya Rengi')),
                ('konum', models.CharField(default='Belirtilmedi', max_length=255, verbose_name='Konum')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Eşya Resmi')),
                ('tarih', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
        ),
    ]
