# Generated by Django 5.1.7 on 2025-03-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kayip_esya', '0002_kayit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kayit',
            name='user',
        ),
    ]
