# Generated by Django 5.1.7 on 2025-04-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayip_esya', '0004_kayit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kayit',
            name='kayit_turu',
            field=models.CharField(choices=[('kaybettim', 'Kaybettim'), ('buldum', 'Buldum')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
