# Generated by Django 5.1.3 on 2025-05-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayip_esya', '0008_bildirim_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayit',
            name='kayit_turu',
            field=models.CharField(choices=[('kaybettim', 'Kaybettim'), ('buldum', 'Buldum'), ('bulundu', 'Bulundu')], max_length=10),
        ),
        migrations.AlterField(
            model_name='kayit',
            name='renk',
            field=models.CharField(choices=[('siyah', 'Siyah'), ('beyaz', 'Beyaz'), ('mavi', 'Mavi'), ('kirmizi', 'Kırmızı'), ('yesil', 'Yeşil'), ('sari', 'Sarı'), ('mor', 'Mor'), ('pembe', 'Pembe'), ('gri', 'Gri'), ('diger', 'Diğer')], default='Seçiniz', max_length=50, verbose_name='Eşya Rengi'),
        ),
        migrations.AlterField(
            model_name='kayit',
            name='tur',
            field=models.CharField(choices=[('canta', 'Çanta'), ('telefon', 'Telefon'), ('cuzdan', 'Cüzdan'), ('anahtar', 'Anahtar'), ('gozluk', 'Gözlük'), ('diger', 'Diğer')], default='Seçiniz', max_length=50, verbose_name='Eşya Türü'),
        ),
    ]
